- <strong>Courage</strong> and <strong>curiosity</strong> in the face of difficult or unexplored challenges
- <strong>Creativity</strong> as a way of doing politics
- <strong>Excellence</strong> and <strong>uniqueness</strong> in terms of social impact
- <strong>Internationality</strong> from the <strong>Mediterranean</strong>
- <strong>Listening</strong>, <strong>adaptability</strong> and <strong>respect</strong> for differences
- <strong>Openness</strong> and <strong>proactivity</strong> as an organizational culture
- <strong>Well-being</strong> and <strong>flexibility</strong> to promote participation
- <strong>Autonomy</strong> and <strong>self-management</strong> of consensus and dialogue
