- <strong>Valentía</strong> y <strong>curiosidad</strong> ante los retos difíciles o inexplorados
- <strong>Creatividad</strong> como forma de hacer política 
- <strong>Excelencia</strong> y <strong>singularidad</strong> en términos de impacto social
- <strong>Internacionalidad</strong> desde el <strong>Mediterráneo<strong>
- <strong>Escucha</strong>, <strong>adaptabilidad</strong> y <strong>respeto</strong> a la diferencia
- <strong>Apertura</strong> y <strong>proactividad</strong> como cultura organizacional 
- <strong>Bienestar</strong> y <strong>flexibilidad</strong> para impulsar la participación
- <strong>Autonomía</strong> y <strong>autogestión</strong> de los consensos y el diálogo
