- Valentía y curiosidad ante los retos difíciles o inexplorados
- Creatividad como forma de hacer política 
- Excelencia y singularidad en términos de impacto social
- Internacionalidad desde el Mediterráneo
- Escucha, adaptabilidad y respeto a la <strong>diferencia</strong>
- Apertura y proactividad como cultura organizacional 
- Bienestar y flexibilidad para impulsar la participación y la motivación personal 
- Autonomía y autogestión de los consensos y el diálogo
