version: '3'
services:
  jekyll:
    build: .
    volumes:
      - ../jekyll-theme-platoniq.net:/jekyll-theme-platoniq.net
      - gems:/usr/local/bundle:delegated
      - .:/platoniq.net
    ports:
      - "4000:4000"
volumes:
  gems: {}
