[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options= ALLOW-FROM https://videos.laguixeta.cat https://peertube.laguixeta.cat

    # Optional: Add CORS headers if needed
    Access-Control-Allow-Origin = "https://videos.laguixeta.cat"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
