[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-src https://videos.laguixeta.cat; default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' https://videos.laguixeta.cat;"

    # Optional: Add CORS headers if needed
    Access-Control-Allow-Origin = "https://videos.laguixeta.cat"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
