budget: Pressupost
colab_btn: Col·labora en el projecte
colaboratos: Col·laboradors
contact_btn: Contactar
info_msg: Per obtenir informació addicional sobre el projecte contracta un dels nostres serveis o contacta'ns.
services: Serveis
team: Membres
share: Compartir
title_prev: 
title_next: