budget: Presupuesto
colab_btn: Colabora con nosotros
colaboratos: Colaboradores
contact_btn: Contactar
info_msg: Para obtener información adicional a cerca del projecto contrata uno de nuestros servicios o contactanos.
services: Servicios
team: Miembros
share: Compartir
title_prev: 
title_next:
private: privado
public: público
looking: en busca de financiación