all_projects: Todos los Proyectos
budget: Presupuesto
colab_btn: Colabora con nosotros
collaborators: Colaboradores
contact_btn: Contactar
info_msg: Para obtener información adicional a cerca del projecto contrata uno de nuestros servicios o contactanos.
services: Servicios
team: Miembros
share: Compartir
title_prev: 
title_next:
private: privado
public: público
looking: en busca de financiación
header_symbol:
  path: /media/site-symbols/project-symbol.png
  alt: project header symbol
info_box: 
  image:
    path: /media/site-symbols/info.png
    alt: info-png
  text: Para obtener información addicional sobre el proyecto porfavor contactanos.
  contact: Contactar